Drop DATABASE IF EXISTS DRAW;

CREATE DATABASE DRAW;

USE DRAW;

CREATE TABLE User(
	student_id INT UNSIGNED NOT NULL PRIMARY KEY,
	name VARCHAR(256) NOT NULL,
	room_preference VARCHAR(256) NOT NULL,
	-- Need to assign time slot as the user submits their form
	timeslot INT UNSIGNED NOT NULL,
	class VARCHAR(256) NOT NULL
);


CREATE TABLE Building(
	building_id INT UNSIGNED NOT NULL PRIMARY KEY,
	name VARCHAR(256) NOT NULL
);


CREATE TABLE Room(
	room_select INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	room_id INT UNSIGNED NOT NULL,
	building_id INT UNSIGNED NOT NULL,
	capacity INT UNSIGNED NOT NULL
	-- FOREIGN KEY (building_id) REFERENCES Building(building_id)
);

CREATE TABLE Reservation(
	res_id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	room_id INT UNSIGNED NOT NULL,
	owner INT UNSIGNED NOT NULL,
	building_id INT UNSIGNED NOT NULL,
	time_stamp INT UNSIGNED NOT NULL
	-- FOREIGN KEY (owner) REFERENCES User (student_id),
	-- FOREIGN KEY (room_id) REFERENCES Room(room_id),
	-- FOREIGN KEY (building_id) REFERENCES Building(building_id)
);



INSERT INTO Building VALUES (01, "Wholford");
INSERT INTO Building VALUES (02, "Green");
INSERT INTO Building VALUES (03, "Boswell");
INSERT INTO Building VALUES (04, "Appleby");


INSERT INTO Room VALUES (NULL, 01, 01, 1);
INSERT INTO Room VALUES (NULL, 02, 01, 1);
INSERT INTO Room VALUES (NULL, 03, 01, 1);
INSERT INTO Room VALUES (NULL, 04, 01, 1);
INSERT INTO Room VALUES (NULL, 05, 01, 1);
INSERT INTO Room VALUES (NULL, 06, 01, 1);
INSERT INTO Room VALUES (NULL, 07, 01, 1);
INSERT INTO Room VALUES (NULL, 08, 01, 1);
INSERT INTO Room VALUES (NULL, 09, 01, 1);
INSERT INTO Room VALUES (NULL, 10, 01, 1);
INSERT INTO Room VALUES (NULL, 11, 01, 1);
INSERT INTO Room VALUES (NULL, 12, 01, 1);

INSERT INTO Room VALUES (NULL, 01, 02, 1);
INSERT INTO Room VALUES (NULL, 02, 02, 1);
INSERT INTO Room VALUES (NULL, 03, 02, 1);
INSERT INTO Room VALUES (NULL, 04, 02, 1);
INSERT INTO Room VALUES (NULL, 05, 02, 1);
INSERT INTO Room VALUES (NULL, 06, 02, 1);
INSERT INTO Room VALUES (NULL, 07, 02, 1);
INSERT INTO Room VALUES (NULL, 08, 02, 1);
INSERT INTO Room VALUES (NULL, 09, 02, 1);
INSERT INTO Room VALUES (NULL, 10, 02, 1);
INSERT INTO Room VALUES (NULL, 11, 02, 1);
INSERT INTO Room VALUES (NULL, 12, 02, 1);



INSERT INTO Room VALUES (NULL, 01, 03, 1);
INSERT INTO Room VALUES (NULL, 02, 03, 1);
INSERT INTO Room VALUES (NULL, 03, 03, 1);
INSERT INTO Room VALUES (NULL, 04, 03, 1);
INSERT INTO Room VALUES (NULL, 05, 03, 1);
INSERT INTO Room VALUES (NULL, 06, 03, 1);
INSERT INTO Room VALUES (NULL, 07, 03, 1);
INSERT INTO Room VALUES (NULL, 08, 03, 1);
INSERT INTO Room VALUES (NULL, 09, 03, 1);
INSERT INTO Room VALUES (NULL, 10, 03, 1);
INSERT INTO Room VALUES (NULL, 11, 03, 1);
INSERT INTO Room VALUES (NULL, 12, 03, 1);

INSERT INTO Room VALUES (NULL, 01, 04, 1);
INSERT INTO Room VALUES (NULL, 02, 04, 1);
INSERT INTO Room VALUES (NULL, 03, 04, 1);
INSERT INTO Room VALUES (NULL, 04, 04, 1);
INSERT INTO Room VALUES (NULL, 05, 04, 1);
INSERT INTO Room VALUES (NULL, 06, 04, 1);
INSERT INTO Room VALUES (NULL, 07, 04, 1);
INSERT INTO Room VALUES (NULL, 08, 04, 1);
INSERT INTO Room VALUES (NULL, 09, 04, 1);
INSERT INTO Room VALUES (NULL, 10, 04, 1);
INSERT INTO Room VALUES (NULL, 11, 04, 1);
INSERT INTO Room VALUES (NULL, 12, 04, 1);